Rename studio create to studio project Rename studio example to studio-create-* Split studio-create into 4 individual commands Fixup the stutio project options to allow passing software suite and version without switches.

diff --git a/libexec/studio-project b/libexec/studio-project
--- a/libexec/studio-project
+++ b/libexec/studio-project
@@ -1,33 +1,33 @@
 #!/usr/bin/env bash
 
-# Usage: studio create -e <product> [-v <version>] [-q <qualifiers>] [-n <dirname> ]
-# Summary: Creates the study area.
+# Usage: studio project [-e,-s] <product> [-v] <version> [-q <qualifiers>] [-n <dirname> ]
+# Summary: Creates a project area for software suite <product>.
 
-# Help: This will create a directory, by default named 'study-area',
+# Help: This will create a directory, by default named 'project',
 # in the current directory, and in it a small directory tree for your
 # work. See 'DIRECTORY STRUCTURE' for complete details on the
 # directory structure that is generated.
 #
-# The create command requires use of a UPS installed product to
+# The project command requires use of a UPS installed product to
 # provide the headers your code will include, the libraries to which
 # your new code will be linked, and the art framework modules and
 # servicesyour FHiCL configuration files will use. Typically this will
 # be the code distribution from an experiment, but it could be any UPS
 # product.
 #
-# If no version is specified, the create command will attempt to
+# If no version is specified, the project command will attempt to
 # identify and use the most recent version of the named
 # product. Specifying a qualifier without explicitly specifying a
 # version is unreliable and should be avoided.
 #
-# If no qualifier is specified, the create command will attempt to use
+# If no qualifier is specified, the project command will attempt to use
 # whatever qualifiers are found for the selected version of the
-# product. If multiple qualifiers are available for that version, the
-# create attempts a reasonable choice. In this condition, it is best
-# to specify qualifiers on the command line.
+# product. If multiple qualifiers are available for that version,
+# project command attempts a reasonable choice. In this condition, 
+# it is best to specify qualifiers on the command line.
 #
-# If -n <dirname> is specified, the created directory will be given
-# the specified name, rather than the default 'study-area'.
+# If -n <dirname> is specified, the project directory will be given
+# the specified name, rather than the default 'project'.
 #
 # DIRECTORY STRUCTURE
 # The generated directory structure is:
@@ -62,142 +62,111 @@
 # the build system.
 #
 # The 'src' directory is where the source code you write will go. Code
-# created by the module skeleton generators will go here
+# generated by the module skeleton generators will go here
 # automatically.
 #
 # 'setup.sh' is a bash script must be 'sourced' in each new shell
 # session in which you want to work on your project.
 # 
 # EXAMPLES
-#    studio create -e lariatsoft -v v06_03_00 -q e10:prof
-#    studio create -e lariatsoft -v v06_03_00 -q e10:prof -n lariatsoft_study
-#    studio create -e dunetpc -v v06_18_01
-#    studio create -e dunetpc -v v06_18_01 -n duntpc_study
-#    studio create -e uboonecode
-#    studio create -e uboonecode -n uboone_study
+#    studio project lariatsoft v06_03_00 -q e10:prof
+#    studio project lariatsoft v06_03_00 -q e10:prof -n lariatsoft_project
+#    studio project dunetpc v06_18_01
+#    studio project dunetpc v06_18_01 -n duntpc_project
+#    studio project uboonecode
+#    studio project uboonecode -n uboone_project
 #
 set -e
 #=========================================READING IN ARGUMENTS============================================
 
-#checking for empty call
-if [ -z "$1" ]; then
-    echo "'studio create' requires specification of a UPS package."
-    echo "Please try 'studio help create'"
-    exit 2
-fi
+
+arrange_opts() {
+    local flags args optstr=$1
+    shift
+
+    while (($#)); do
+        case $1 in
+            --) args+=("$@")
+                break;
+                ;;
+            -*) flags+=("$1")
+                if [[ $optstr == *"${1: -1}:"* ]]; then
+                    flags+=("$2")
+                    shift
+                fi
+                ;;
+            * ) args+=("$1")
+                ;;
+        esac
+        shift
+    done
+    OPTARR=("${flags[@]}" "${args[@]}")
+}
+
+#default values
+name=project
+unset exp
+unset qual
+unset rep
 
 #assigning arguments
-#first option
-if [ "$1" == "-e" ]; then
-    exp=$2
+OPTIND=
+OPTARR=
+optstring=s:v:q:r:n:
+
+arrange_opts "$optstring" "$@"
+set -- "${OPTARR[@]}"
+
+OPTIND=1
+while getopts $optstring opt;do
+    case ${opt} in 
+           s|e) 
+                exp="$OPTARG"
+                ;;
+           v) 
+                ver="$OPTARG"
+                ;;
+           q) 
+                qual="$OPTARG"
+                ;;
+           r)
+                rep="$OPTARG"
+                ;;
+           n)
+                name="$OPTARG"
+                ;;
+     esac 
+done
+
+shift $((OPTIND-1))
+
+#checking for empty call ans positional arguments
+if [ $# == 0 ] ; then
+    echo "'studio project' requires specification of a software suite."
+    echo "Please try 'studio help project'"
+    exit 2
+else
+    exp=$1;
+    shift;
+    if [ $# != 0 ] ; then 
+        ver=$1
+        shift
+        echo $@
+    fi
 fi
-if [ "$1" == "-v" ]; then
-    ver=$2
-fi
-if [ "$1" == "-q" ]; then
-    qual=$2
-fi
-if [ "$1" == "-r" ]; then
-    rep=$2
-fi
-if [ "$1" == "-n" ]; then
-    name=$2
-fi
-##second option
-if [ "$3" == "-e" ]; then
-    exp=$4
-fi
-if [ "$3" == "-v" ]; then
-    ver=$4
-fi
-if [ "$3" == "-q" ]; then
-    qual=$4
-fi
-if [ "$3" == "-r" ]; then
-    rep=$4
-fi
-if [ "$3" == "-n" ]; then
-    name=$4
-fi
-##third option
-if [ "$5" == "-e" ]; then
-    exp=$6
-fi
-if [ "$5" == "-v" ]; then
-    ver=$6
-fi
-if [ "$5" == "-q" ]; then
-    qual=$6
-fi
-if [ "$5" == "-r" ]; then
-    rep=$6
-fi
-if [ "$5" == "-n" ]; then
-    name=$6
-fi
-##third option
-if [ "$7" == "-e" ]; then
-    exp=$8
-fi
-if [ "$7" == "-v" ]; then
-    ver=$8
-fi
-if [ "$7" == "-q" ]; then
-    qual=$8
-fi
-if [ "$7" == "-r" ]; then
-    rep=$8
-fi
-if [ "$7" == "-n" ]; then
-    name=$8
-fi
+
 
 # dummy catchers
 if [ -z "$exp" ] && [ -z "$rep" ]; then
-    echo "Please specify a UPS product name."
+    echo "Please specify a software suite name."
     exit
 fi
 
 if [ ! -z "$exp" ] && [ ! -z "$rep" ]; then
-    echo "You cannot specify a UPS product *and* a repository."
+    echo "You cannot specify a software suite name *and* a repository."
     exit
 fi
 
-if [ "$exp" == "-n" ] || [ "$exp" == "-v" ] || [ "$exp" == "-q" ]; then
-    echo "Please check syntax."
-    exit
-fi
-
-if [ "$name" == "-e" ] || [ "$name" == "-v" ] || [ "$exp" == "-q" ]; then
-    echo "Please check syntax."
-    exit
-fi
-
-if [ "$ver" == "-e" ] || [ "$ver" == "-n" ] || [ "$ver" == "-q" ]; then
-    echo "Please check syntax."
-    exit
-fi
-
-if [ "$qual" == "-e" ] || [ "$qual" == "-n" ] || [ "$qual" == "-v" ]; then
-    echo "Please check syntax."
-    exit
-fi
-
-# empty qual messages
-if [ -z "$ver" ] && [ -z "$rep" ]; then
-#echo "Default version is being used."
-    echo "No version specified."
-fi
-
-if [ -z "$qual" ] && [ -z "$rep" ]; then
-#echo "Default qualifiers is being used used."
-    echo "No qualifiers specified."
-fi
-
-if [ -z "$name" ] && [ -z "$rep" ]; then
-    name=study-area
-    echo "Default study-area directory name being used."
-fi
 
 #=========================================================================================================
 #==============================================MAKING=====================================================
@@ -210,8 +179,6 @@ fi
 
 #art workbook garbage
 if [ "$rep" == "art-workbook" ]; then
-    echo "hmm... you want the art workbook.."
-    echo "here we go..."
     git clone http://cdcvs.fnal.gov/projects/art-workbook
     mv $PWD/art-workbook $PWD/$name
     mv $PWD/$name/art-workbook $PWD/$name/src
@@ -235,18 +202,12 @@ else
   LD_LIBRARY_PATH=$BUILD_DIR/lib:\$LD_LIBRARY_PATH
 fi
 EOF
-#temp fix for studio not being an installed prod?
-echo "$PWD"
+    echo ""
+    echo "The project directory '${name}' has been created."
+    echo "Remember to source '${name}/setup.sh' in each new shell"
+    echo "Use 'studio help' for more details."
+    echo ""
 
-echo ""
-echo "    ++++++++++++++++++++++++++++++++++++++++++    "
-echo "    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-    "
-echo "    ========== study area created! ===========    "
-echo "    === source setup every time you login! ===    "
-echo "    === studio help or studio help command ===    "
-echo "    ========== for more details!   ===========    "
-echo "    ++++++++++++++++++++++++++++++++++++++++++    "
-echo "    -+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+    "
 else
 
 #NORMAL DIRECTORY TREE
@@ -255,7 +216,7 @@ else
         exit 1
     fi
 
-    mkdir -p "$name" || ( echo "Failed to create directory ${name}" ; exit 1)
+    mkdir -p "$name" || ( echo "Failed to project directory ${name}" ; exit 1)
     cd "$name"
     TOP=${PWD}
     mkdir build
@@ -263,11 +224,6 @@ else
     mkdir ext
     mkdir src
 
-    echo ""
-    echo "The directory '${name}' has been created."
-    echo "Remember to source '${name}/setup.sh' in each new shell"
-    echo "Use 'studio help' for more details."
-    echo ""
 
 # === may need to change where this is done ===
 # === probably after the if switch for wkbk ===
@@ -288,44 +244,54 @@ else
 # --- but for now this works                 ---
 # ----------------------------------------------
 
+echo "Creating the project directory '${name}'."
 #no version specified but qual specified
     if [ -z "$ver" ] && [ ! -z "$qual" ]; then
         ver=$(ups list -aK+ "$exp" | grep $qual | sort | tail -1 | awk '{print $2}'| sed -e's/"//g')
-        echo "no version specified but qual specified..."
-        echo "latest version used..."
-        echo "setup $exp $ver -q $qual"
+        echo ""
+        echo "  no version specified but qualifier specified..."
+        echo "  latest version will be used..."
+        echo "  setup $exp $ver -q $qual"
+        echo "  added to setup.sh script"
         echo ""
     fi
 #no qual specified but version specified
     if [ -z "$qual" ] && [ ! -z "$ver" ]; then
         qual=$(ups list -aK+ $exp | grep $ver | sort | tail -1 | awk '{print $4}'| sed -e's/"//g')
-        echo "no qual specified but ver specified..."
-        echo "latest qual used..."
-        echo "setup $exp $ver -q $qual"
+        echo ""
+        echo "  no qualifier specified but version specified..."
+        echo "  latest qualifier will be used..."
+        echo "  setup $exp $ver -q $qual"
+        echo "  added to setup.sh script"
         echo ""
     fi
 #no version and no qual specified?
     if [ -z "$ver" ] && [ -z "$qual"]; then
         ver=$(ups list -aK+ "$exp" | sort | tail -1 | awk '{print $2}'| sed -e's/"//g')
         qual=$(ups list -aK+ $exp | sort | tail -1 | awk '{print $4}'| sed -e's/"//g')
-        echo "no qual specified and no ver specified..."
-        echo "default qual and version used..."
-        echo "$exp $ver -q $qual"
+        echo ""
+        echo "  no qualifier and no version specified..."
+        echo "  latest qualifier and version will be used..."
+        echo "  setup $exp $ver -q $qual"
+        echo "  added to setup.sh script"
         echo ""
     fi
+    echo ""
+    echo "The project directory '${name}' has been created."
+    echo "Remember to source '${name}/setup.sh' in each new shell"
+    echo "Use 'studio help' for more details."
+    echo ""
 
 # writing the setup script
 
     cat << EOF > setup.sh
 #!/usr/bin/env bash
 #Setup script for "$exp" with requested version and qualifiers (may default to current version)
-# TODO: avoid hard-coding the studio version here
 setup studio
 setup $exp $ver -q $qual
 export STUDIO_PROJECT_BUILD_PATH=$BUILD_DIR
 export STUDIO_PROJECT_SRC_PATH=$SRC_DIR
-os_name=$(uname -s)
-if [ \$os_name = "Darwin" ]; then
+if [ \$(uname -s) = "Darwin" ]; then
   DYLD_LIBRARY_PATH=$BUILD_DIR/lib:\$DYLD_LIBRARY_PATH
 else
   LD_LIBRARY_PATH=$BUILD_DIR/lib:\$LD_LIBRARY_PATH
@@ -418,7 +384,7 @@ cat << 'EOF' > CMakeLists.txt
 #CMakeLists for "$exp" with specific directory tree
 include(helpers.cmake)
 cmake_minimum_required(VERSION 2.8.9)
-project(study_area)
+project(studio_generated)
 set(CMAKE_CXX_FLAGS "-std=c++14")
 
 if (${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
