Fix some missing variables. Let ups configure most of the files except studio.current.in.

diff --git a/libexec/studio-project b/libexec/studio-project
--- a/libexec/studio-project
+++ b/libexec/studio-project
@@ -208,11 +208,6 @@ EOF
 
 else
 
-# === may need to change where this is done ===
-# === probably after the if switch for wkbk ===
-    BUILD_DIR=$TOP/build
-    EXT_PATH=$TOP/ext
-    SRC_DIR=$TOP/src
 
 #=========================================================================================================
 #==============================================MAKING=====================================================
@@ -295,18 +290,21 @@ echo "Creating the project directory '${name}'."
         exit 1
     fi
 
-    mkdir -p "$name" || ( echo "Failed to project directory ${name}" ; exit 1)
-    cd "$name"
+    mkdir -p "$PWD/$name" || ( echo "Failed to project directory ${name}" ; exit 1)
+    cd "$PWD/$name"
     TOP=${PWD}
-    mkdir build
-    touch build/CMakeCache.txt
-    mkdir ext
-    mkdir src
+    mkdir ${TOP}/build
+    touch ${TOP}/build/CMakeCache.txt
+    mkdir ${TOP}/ext
+    mkdir ${TOP}/src
+    BUILD_DIR=$TOP/build
+    EXT_PATH=$TOP/ext
+    SRC_DIR=$TOP/src
 
 
 # writing the setup script
 
-    cat << EOF > setup.sh
+    cat << EOF > ${TOP}/setup.sh
 #!/usr/bin/env bash
 #Setup script for "$exp" with requested version and qualifiers (may default to current version)
 setup studio
